# Site settings
title: Home
header-img: img/home-bg.jpg
email: hello@vinaynaidu.com
description: "Welcome to the musings of a curious coder"
baseurl: ""
url: "http://vinaynaidu.com"
twitter_username: padfootprong
github_username:  vinaynaidu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
